### PR TITLE
Move query to a seperate command

### PR DESCRIPTION
**Pull request by hannahhoward**
# Goals

I realize this query is very temporary, but I want to make sure I'm doing this right by moving it to a seperate command that I can run from a spot instance with `kubectl exec`. Is this the correct way to do it? Or perhaps move to a seperate docker entirely?

Also I do need to run this query, if only once. To make sure I get the proper data for this week.

### CODE REVIEW

**Review by kylehuntsman — COMMENTED** [review]
I don't believe you're going to be able to get kubectl exec access to this image to perform your stats command due to the entrypoint being the recorder command. From my knowledge, there is no ad-hoc way to tell the k8s pod to create this image with a --entrypoint docker run override command and _not_ also have it default to running the recorder command.

**Comment by masih** [comment]
@kylehuntsman there is. Look at pod spec args and command.

**Review by masih — APPROVED** [review]

**Comment by masih** [comment]
@hannahhoward Is there a reason for not using `postgres` image straight up and connecting to db via `psql` it comes with?

You can do it like this:
```
 kubectl run -n autoretrieve -i --tty hannah-postgres --image=postgres -- bash
```

That gives you a bash session with `psql` binary present that has network reachability to the database.

Once finished, you can then clean up the pod like this:
```
 kubectl delete po -n autoretrieve hannah-postgres
```

If the aim is to run a query then the above would remove the need for this PR entirely.

**Comment by hannahhoward** [comment]
indeed, we don't need it. closing.

**Pull request closed without merging**
